{% set name = "chemml" %}
{% set version = "1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemml-{{ version }}.tar.gz
  sha256: 0efae4b5b8c730aca058ef87b203914b384ede017449be185221a69635d0885a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - future
    - python-graphviz
    - h5py
    - ipywidgets
    - lxml
    - matplotlib-base >=1.5.1
    - numpy
    - openpyxl
    - pandas
    - python >=3.6
    - scikit-learn
    - scipy
    - seaborn
    - six
    - tensorflow
    - wget
    - rdkit
    - openbabel

test:
  imports:
    - chemml
    - chemml.chem

about:
  home: https://hachmannlab.github.io/chemml/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ChemML is a machine learning and informatics program suite for the chemical and materials sciences.
  description: |
    ChemML is a machine learning and informatics program suite for the
    analysis, mining, and modeling of chemical and materials data.
  doc_url: https://hachmannlab.github.io/chemml/
  dev_url: https://github.com/hachmannlab/chemml

extra:
  recipe-maintainers:
    - jan-janssen
